# Generated by Django 4.2.3 on 2023-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='questions/'),
        ),
    ]
